[workspace]
channels = ["https://prefix.dev/brads-forge", "conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
init = "task init"

[tasks.code]
depends-on = ["init"]
cmd = "code ."

[dependencies]
cocogitto = ">=6.5.0,<7"
deno = ">=2.6.8,<2.7"
dprint = ">=0.51.1,<0.52"
gh = ">=2.86.0,<3"
lefthook = ">=2.1.0,<3"
task = ">=3.48.0,<4"
